all:
  children:
    NSIS-PMX-13:
      hosts:
        CSD-ARTRDS01.nsis.local:
        CSD-CMSRDS01.nsis.local:
        CSD-DC01.nsis.local:
        CSD-HLSGUAC01.nsis.local:
        CSD-INCOGUAC01.nsis.local:
        CSD-JDSGUAC01.nsis.local:
        CSD-PLMGUAC01.nsis.local:
        CSD-RDB01.nsis.local:
        NSIS-DC01.nsis.local:
        NSIS-FOG01.nsis.local:
        NSIS-SBC01.nsis.local:
        VBK-CLG02.nsis.local:
        VBK-EXO01.nsis.local:
        VBK-REPO02.nsis.local:
        VBK-SPC01.nsis.local:
        VBK-VBR01.nsis.local:
        bstk-svc-rxapp01.nsis.local:
        bstk-svc-rxmongo01.nsis.local:
        nsis-ceph01.nsis.local:
        nsis-cephadm01.nsis.local:
        nsis-publb02.nsis.local:
        nsis-test-vault.nsis.local:
        nsis-ubuntu-smb01.nsis.local:
        nsis-ubuntu-smbq0.nsis.local:
    NSIS-PMX-14:
      hosts:
        BSTK-SVC-DEVSIMS01.nsis.local:
        BSTK-SVC-LOGSRV01.nsis.local:
        BSTK-SVC-PAULTEC-ONESPARK01.nsis.local:
        BSTK-SVC-SWITCHBACKUP01.nsis.local:
        CENTOS-7-TEMPLATE.nsis.local:
        DEBIAN-10-TEMPLATE.nsis.local:
        NSIS-SQL01.nsis.local:
        NSIS-SQL02.nsis.local:
        NSIS-VSCAN.nsis.local:
        UBUNTU-20.04-TEMPLATE.nsis.local:
        V2V-TEST.nsis.local:
        V2V-TEST2.nsis.local:
        WIN2019-TEMPLATE.nsis.local:
        csd-ansible01.nsis.local:
        csd-ipam01.nsis.local:
        csd-lb01.nsis.local:
        csd-lb02.nsis.local:
        csd-vault01.nsis.local:
        csd-vault02.nsis.local:
        csd-vault03.nsis.local:
        nsis-ceph02.nsis.local:
        nsis-smb01.nsis.local:
        nsis-smb02.nsis.local:
        w2k19-srv-ci-tmplt.nsis.local:
    NSIS-PMX-15:
      hosts:
        CSD-DC02.nsis.local:
        CSD-HLSRDS01.nsis.local:
        CSD-INCORDS01.nsis.local:
        CSD-PLMRDS01.nsis.local:
        CSD-ZBX01.nsis.local:
        NSIS-DC02.nsis.local:
        NSIS-MGT01.nsis.local:
        NSIS-SBC02.nsis.local:
        NSIS-TEST01.nsis.local:
        NSIS-ZBX01.nsis.local:
        VBK-CLG01.nsis.local:
        VBK-REPO01.nsis.local:
        VBK-WAC01.nsis.local:
        bstk-svc-devmsgapp01.nsis.local:
        bstk-svc-rxapp02.nsis.local:
        bstk-svc-rxmongo02.nsis.local:
        nsis-ceph03.nsis.local:
        nsis-ipam.nsis.local:
        nsis-publb01.nsis.local:
        nsis-ubuntu-smb02.nsis.local:
  hosts:
    BSTK-SVC-DEVSIMS01.nsis.local:
    BSTK-SVC-LOGSRV01.nsis.local:
    BSTK-SVC-PAULTEC-ONESPARK01.nsis.local:
    BSTK-SVC-SWITCHBACKUP01.nsis.local:
    CENTOS-7-TEMPLATE.nsis.local:
    CSD-ARTRDS01.nsis.local:
    CSD-CMSRDS01.nsis.local:
    CSD-DC01.nsis.local:
    CSD-DC02.nsis.local:
    CSD-HLSGUAC01.nsis.local:
    CSD-HLSRDS01.nsis.local:
    CSD-INCOGUAC01.nsis.local:
    CSD-INCORDS01.nsis.local:
    CSD-JDSGUAC01.nsis.local:
    CSD-PLMGUAC01.nsis.local:
    CSD-PLMRDS01.nsis.local:
    CSD-RDB01.nsis.local:
    CSD-ZBX01.nsis.local:
    DEBIAN-10-TEMPLATE.nsis.local:
    NSIS-DC01.nsis.local:
    NSIS-DC02.nsis.local:
    NSIS-FOG01.nsis.local:
    NSIS-MGT01.nsis.local:
    NSIS-PMX-13.nsis.local:
    NSIS-PMX-14.nsis.local:
    NSIS-PMX-15.nsis.local:
    NSIS-SBC01.nsis.local:
    NSIS-SBC02.nsis.local:
    NSIS-SQL01.nsis.local:
    NSIS-SQL02.nsis.local:
    NSIS-TEST01.nsis.local:
    NSIS-VSCAN.nsis.local:
    NSIS-ZBX01.nsis.local:
    UBUNTU-20.04-TEMPLATE.nsis.local:
    V2V-TEST.nsis.local:
    V2V-TEST2.nsis.local:
    VBK-CLG01.nsis.local:
    VBK-CLG02.nsis.local:
    VBK-EXO01.nsis.local:
    VBK-REPO01.nsis.local:
    VBK-REPO02.nsis.local:
    VBK-SPC01.nsis.local:
    VBK-VBR01.nsis.local:
    VBK-WAC01.nsis.local:
    WIN2019-TEMPLATE.nsis.local:
    bstk-svc-devmsgapp01.nsis.local:
    bstk-svc-rxapp01.nsis.local:
    bstk-svc-rxapp02.nsis.local:
    bstk-svc-rxmongo01.nsis.local:
    bstk-svc-rxmongo02.nsis.local:
    csd-ansible01.nsis.local:
    csd-ipam01.nsis.local:
    csd-lb01.nsis.local:
    csd-lb02.nsis.local:
    csd-vault01.nsis.local:
    csd-vault02.nsis.local:
    csd-vault03.nsis.local:
    nsis-ceph01.nsis.local:
    nsis-ceph02.nsis.local:
    nsis-ceph03.nsis.local:
    nsis-cephadm01.nsis.local:
    nsis-ipam.nsis.local:
    nsis-publb01.nsis.local:
    nsis-publb02.nsis.local:
    nsis-smb01.nsis.local:
    nsis-smb02.nsis.local:
    nsis-test-vault.nsis.local:
    nsis-ubuntu-smb01.nsis.local:
    nsis-ubuntu-smb02.nsis.local:
    nsis-ubuntu-smbq0.nsis.local:
    w2k19-srv-ci-tmplt.nsis.local:
